[package]
name = "wlclient"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1"
tokio = { version = "1.0", default-features = false, features = ["io-util", "macros", "net", "rt", "time"] }

[profile.release]
lto = true
panic = 'abort'
